services:

  solr:
    build:
      context: ./docker/solr
    environment:
      TZ: ${TZ:-Europe/Berlin}
      SOLR_HOST: 0.0.0.0
        #      SOLR_MODULES: analysis-extras
    volumes:
      - ./docker/solr/etc/solr/configsets:/var/solr/data/configsets
    ports:
      - 9091:8983
    networks:
      - atoolo-e2e-test

  php:
    image: e2e-test-php:${MATRIX_PHP_VERSION}
    build:
      context: ./docker/php/${MATRIX_PHP_VERSION}
#    user: ${USERID}:${GROUPID}
    environment:
      TZ: ${TZ:-Europe/Berlin}
      SOLR_HOST: solr
      SOLR_PORT: 8983
      IES_WEBNODE_HOME: /srv/sitepark/ies-webnode
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      RESOURCE_ROOT: /var/www/atoolo-e2e-test/www/resources
      MAILER_PORT: 1025
      MAILER_HOST: mailer
      MAILER_DSN: smtp://mailer:1025
      #XDEBUG_MODE: debug,develop,profile
      #XDEBUG_SESSION: PHPSTORM
    volumes:
      - ./resources:/var/www/atoolo-e2e-test/www/resources
      - ./docker/php/bin:/tools
      - ./docker/php/etc/apache2/sites-enabled/atoolo-e2e-test.conf:/etc/apache2/sites-enabled/atoolo-e2e-test.conf
      - ./docker/php/etc/ies-webnode/config/realm.properties:/srv/sitepark/ies-webnode/config/realm.properties
      - ./docker/php/etc/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./data/php/.bash_history:/root/.bash_history
#      - ./data/php/.composer:/var/www/.composer
    ports:
      - 9090:80
      - 9191:8000
    networks:
      - atoolo-e2e-test
  mailer:
    image: axllent/mailpit
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    ports:
      - 8025:8025
      - 1025:1025
    networks:
      - atoolo-e2e-test

networks:
  atoolo-e2e-test:
