<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit75e7f8d848176580e9902a32f6f14640
{
    public static $files = array (
        '6e3fae29631ef280660b3cdad06f25a8' => __DIR__ . '/..' . '/symfony/deprecation-contracts/function.php',
        '0e6d7bf4a5811bfa5cf40c5ccd6fae6a' => __DIR__ . '/..' . '/symfony/polyfill-mbstring/bootstrap.php',
        '606a39d89246991a373564698c2d8383' => __DIR__ . '/..' . '/symfony/polyfill-php85/bootstrap.php',
        '667aeda72477189d0494fecd327c3641' => __DIR__ . '/..' . '/symfony/var-dumper/Resources/functions/dump.php',
        'e69f7f6ee287b969198c3c9d6777bd38' => __DIR__ . '/..' . '/symfony/polyfill-intl-normalizer/bootstrap.php',
        '8825ede83f2f289127722d4e842cf7e8' => __DIR__ . '/..' . '/symfony/polyfill-intl-grapheme/bootstrap.php',
        'b6b991a57620e2fb6b2f66f03fe9ddc2' => __DIR__ . '/..' . '/symfony/string/Resources/functions.php',
        '662a729f963d39afe703c9d9b7ab4a8c' => __DIR__ . '/..' . '/symfony/polyfill-php83/bootstrap.php',
        '2203a247e6fda86070a5e4e07aed533a' => __DIR__ . '/..' . '/symfony/clock/Resources/now.php',
        '89efb1254ef2d1c5d80096acd12c4098' => __DIR__ . '/..' . '/twig/twig/src/Resources/core.php',
        'ffecb95d45175fd40f75be8a23b34f90' => __DIR__ . '/..' . '/twig/twig/src/Resources/debug.php',
        'c7baa00073ee9c61edf148c51917cfb4' => __DIR__ . '/..' . '/twig/twig/src/Resources/escaper.php',
        'f844ccf1d25df8663951193c3fc307c8' => __DIR__ . '/..' . '/twig/twig/src/Resources/string_loader.php',
        '9d2b9fc6db0f153a0a149fefb182415e' => __DIR__ . '/..' . '/symfony/polyfill-php84/bootstrap.php',
        'ace6d88241f812b4accb2d847454aef6' => __DIR__ . '/..' . '/halaxa/json-machine/src/functions.php',
        'f598d06aa772fa33d905e87be6398fb1' => __DIR__ . '/..' . '/symfony/polyfill-intl-idn/bootstrap.php',
        '9e4824c5afbdc1482b6025ce3d4dfde8' => __DIR__ . '/..' . '/league/csv/src/functions_include.php',
        'a1105708a18b76903365ca1c4aa61b02' => __DIR__ . '/..' . '/symfony/translation/Resources/functions.php',
        'f278094c42a52b6bff77f375d59c1278' => __DIR__ . '/..' . '/twig/markdown-extra/Resources/functions.php',
    );

    public static $prefixLengthsPsr4 = array (
        'p' => 
        array (
            'phpDocumentor\\Reflection\\' => 25,
        ),
        'h' => 
        array (
            'hollodotme\\FastCGI\\' => 19,
        ),
        'W' => 
        array (
            'Webmozart\\Assert\\' => 17,
        ),
        'T' => 
        array (
            'Twig\\Extra\\TwigExtraBundle\\' => 27,
            'Twig\\Extra\\Markdown\\' => 20,
            'Twig\\' => 5,
        ),
        'S' => 
        array (
            'Symfony\\Runtime\\Symfony\\Component\\' => 34,
            'Symfony\\Polyfill\\Php85\\' => 23,
            'Symfony\\Polyfill\\Php84\\' => 23,
            'Symfony\\Polyfill\\Php83\\' => 23,
            'Symfony\\Polyfill\\Mbstring\\' => 26,
            'Symfony\\Polyfill\\Intl\\Normalizer\\' => 33,
            'Symfony\\Polyfill\\Intl\\Idn\\' => 26,
            'Symfony\\Polyfill\\Intl\\Grapheme\\' => 31,
            'Symfony\\Flex\\' => 13,
            'Symfony\\Contracts\\Translation\\' => 30,
            'Symfony\\Contracts\\Service\\' => 26,
            'Symfony\\Contracts\\HttpClient\\' => 29,
            'Symfony\\Contracts\\EventDispatcher\\' => 34,
            'Symfony\\Contracts\\Cache\\' => 24,
            'Symfony\\Component\\Yaml\\' => 23,
            'Symfony\\Component\\VarExporter\\' => 30,
            'Symfony\\Component\\VarDumper\\' => 28,
            'Symfony\\Component\\Validator\\' => 28,
            'Symfony\\Component\\TypeInfo\\' => 27,
            'Symfony\\Component\\Translation\\' => 30,
            'Symfony\\Component\\String\\' => 25,
            'Symfony\\Component\\Serializer\\' => 29,
            'Symfony\\Component\\Security\\Http\\' => 32,
            'Symfony\\Component\\Security\\Csrf\\' => 32,
            'Symfony\\Component\\Security\\Core\\' => 32,
            'Symfony\\Component\\Scheduler\\' => 28,
            'Symfony\\Component\\Runtime\\' => 26,
            'Symfony\\Component\\Routing\\' => 26,
            'Symfony\\Component\\RateLimiter\\' => 30,
            'Symfony\\Component\\PropertyInfo\\' => 31,
            'Symfony\\Component\\PropertyAccess\\' => 33,
            'Symfony\\Component\\Process\\' => 26,
            'Symfony\\Component\\PasswordHasher\\' => 33,
            'Symfony\\Component\\OptionsResolver\\' => 34,
            'Symfony\\Component\\Mime\\' => 23,
            'Symfony\\Component\\Messenger\\' => 28,
            'Symfony\\Component\\Mailer\\' => 25,
            'Symfony\\Component\\Lock\\' => 23,
            'Symfony\\Component\\HttpKernel\\' => 29,
            'Symfony\\Component\\HttpFoundation\\' => 33,
            'Symfony\\Component\\HttpClient\\' => 29,
            'Symfony\\Component\\Finder\\' => 25,
            'Symfony\\Component\\Filesystem\\' => 29,
            'Symfony\\Component\\ExpressionLanguage\\' => 37,
            'Symfony\\Component\\EventDispatcher\\' => 34,
            'Symfony\\Component\\ErrorHandler\\' => 31,
            'Symfony\\Component\\Dotenv\\' => 25,
            'Symfony\\Component\\DependencyInjection\\' => 38,
            'Symfony\\Component\\Console\\' => 26,
            'Symfony\\Component\\Config\\' => 25,
            'Symfony\\Component\\Clock\\' => 24,
            'Symfony\\Component\\Cache\\' => 24,
            'Symfony\\Bundle\\TwigBundle\\' => 26,
            'Symfony\\Bundle\\SecurityBundle\\' => 30,
            'Symfony\\Bundle\\MonologBundle\\' => 29,
            'Symfony\\Bundle\\FrameworkBundle\\' => 31,
            'Symfony\\Bridge\\Twig\\' => 20,
            'Symfony\\Bridge\\Monolog\\' => 23,
            'Soundasleep\\' => 12,
            'Solarium\\' => 9,
        ),
        'R' => 
        array (
            'RRule\\' => 6,
        ),
        'P' => 
        array (
            'Psr\\Log\\' => 8,
            'Psr\\Http\\Message\\' => 17,
            'Psr\\Http\\Client\\' => 16,
            'Psr\\EventDispatcher\\' => 20,
            'Psr\\Container\\' => 14,
            'Psr\\Clock\\' => 10,
            'Psr\\Cache\\' => 10,
            'Phpro\\ApiProblem\\' => 17,
            'Phpro\\ApiProblemBundle\\' => 23,
            'PHPStan\\PhpDocParser\\' => 21,
        ),
        'O' => 
        array (
            'Overblog\\GraphQLBundle\\' => 23,
            'Opis\\Uri\\' => 9,
            'Opis\\String\\' => 12,
            'Opis\\JsonSchema\\' => 16,
        ),
        'M' => 
        array (
            'Murtukov\\PHPCodeGenerator\\' => 26,
            'Monolog\\' => 8,
        ),
        'L' => 
        array (
            'Lexik\\Bundle\\JWTAuthenticationBundle\\' => 37,
            'League\\HTMLToMarkdown\\' => 22,
            'League\\Csv\\' => 11,
            'Lcobucci\\JWT\\' => 13,
        ),
        'J' => 
        array (
            'JsonMachine\\' => 12,
        ),
        'G' => 
        array (
            'GraphQL\\' => 8,
        ),
        'E' => 
        array (
            'Eluceo\\iCal\\' => 12,
            'Egulias\\EmailValidator\\' => 23,
        ),
        'D' => 
        array (
            'Doctrine\\Deprecations\\' => 22,
            'Doctrine\\Common\\Lexer\\' => 22,
        ),
        'C' => 
        array (
            'Cron\\' => 5,
        ),
        'A' => 
        array (
            'Atoolo\\WebAccount\\' => 18,
            'Atoolo\\Seo\\' => 11,
            'Atoolo\\Security\\' => 16,
            'Atoolo\\Search\\' => 14,
            'Atoolo\\Runtime\\Check\\' => 21,
            'Atoolo\\Runtime\\' => 15,
            'Atoolo\\Rewrite\\' => 15,
            'Atoolo\\Resource\\' => 16,
            'Atoolo\\Microsite\\' => 17,
            'Atoolo\\GraphQL\\Search\\' => 22,
            'Atoolo\\Form\\' => 12,
            'Atoolo\\EventsCalendar\\' => 22,
            'Atoolo\\Deployment\\' => 18,
            'Atoolo\\CityGov\\' => 15,
            'Atoolo\\CityCall\\' => 16,
            'App\\Tests\\' => 10,
            'App\\' => 4,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'phpDocumentor\\Reflection\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpdocumentor/reflection-common/src',
            1 => __DIR__ . '/..' . '/phpdocumentor/reflection-docblock/src',
            2 => __DIR__ . '/..' . '/phpdocumentor/type-resolver/src',
        ),
        'hollodotme\\FastCGI\\' => 
        array (
            0 => __DIR__ . '/..' . '/hollodotme/fast-cgi-client/src',
        ),
        'Webmozart\\Assert\\' => 
        array (
            0 => __DIR__ . '/..' . '/webmozart/assert/src',
        ),
        'Twig\\Extra\\TwigExtraBundle\\' => 
        array (
            0 => __DIR__ . '/..' . '/twig/extra-bundle',
        ),
        'Twig\\Extra\\Markdown\\' => 
        array (
            0 => __DIR__ . '/..' . '/twig/markdown-extra',
        ),
        'Twig\\' => 
        array (
            0 => __DIR__ . '/..' . '/twig/twig/src',
        ),
        'Symfony\\Runtime\\Symfony\\Component\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/runtime/Internal',
        ),
        'Symfony\\Polyfill\\Php85\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-php85',
        ),
        'Symfony\\Polyfill\\Php84\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-php84',
        ),
        'Symfony\\Polyfill\\Php83\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-php83',
        ),
        'Symfony\\Polyfill\\Mbstring\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-mbstring',
        ),
        'Symfony\\Polyfill\\Intl\\Normalizer\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-intl-normalizer',
        ),
        'Symfony\\Polyfill\\Intl\\Idn\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-intl-idn',
        ),
        'Symfony\\Polyfill\\Intl\\Grapheme\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/polyfill-intl-grapheme',
        ),
        'Symfony\\Flex\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/flex/src',
        ),
        'Symfony\\Contracts\\Translation\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/translation-contracts',
        ),
        'Symfony\\Contracts\\Service\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/service-contracts',
        ),
        'Symfony\\Contracts\\HttpClient\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/http-client-contracts',
        ),
        'Symfony\\Contracts\\EventDispatcher\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/event-dispatcher-contracts',
        ),
        'Symfony\\Contracts\\Cache\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/cache-contracts',
        ),
        'Symfony\\Component\\Yaml\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/yaml',
        ),
        'Symfony\\Component\\VarExporter\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/var-exporter',
        ),
        'Symfony\\Component\\VarDumper\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/var-dumper',
        ),
        'Symfony\\Component\\Validator\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/validator',
        ),
        'Symfony\\Component\\TypeInfo\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/type-info',
        ),
        'Symfony\\Component\\Translation\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/translation',
        ),
        'Symfony\\Component\\String\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/string',
        ),
        'Symfony\\Component\\Serializer\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/serializer',
        ),
        'Symfony\\Component\\Security\\Http\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/security-http',
        ),
        'Symfony\\Component\\Security\\Csrf\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/security-csrf',
        ),
        'Symfony\\Component\\Security\\Core\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/security-core',
        ),
        'Symfony\\Component\\Scheduler\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/scheduler',
        ),
        'Symfony\\Component\\Runtime\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/runtime',
        ),
        'Symfony\\Component\\Routing\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/routing',
        ),
        'Symfony\\Component\\RateLimiter\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/rate-limiter',
        ),
        'Symfony\\Component\\PropertyInfo\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/property-info',
        ),
        'Symfony\\Component\\PropertyAccess\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/property-access',
        ),
        'Symfony\\Component\\Process\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/process',
        ),
        'Symfony\\Component\\PasswordHasher\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/password-hasher',
        ),
        'Symfony\\Component\\OptionsResolver\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/options-resolver',
        ),
        'Symfony\\Component\\Mime\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/mime',
        ),
        'Symfony\\Component\\Messenger\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/messenger',
        ),
        'Symfony\\Component\\Mailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/mailer',
        ),
        'Symfony\\Component\\Lock\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/lock',
        ),
        'Symfony\\Component\\HttpKernel\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/http-kernel',
        ),
        'Symfony\\Component\\HttpFoundation\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/http-foundation',
        ),
        'Symfony\\Component\\HttpClient\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/http-client',
        ),
        'Symfony\\Component\\Finder\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/finder',
        ),
        'Symfony\\Component\\Filesystem\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/filesystem',
        ),
        'Symfony\\Component\\ExpressionLanguage\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/expression-language',
        ),
        'Symfony\\Component\\EventDispatcher\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/event-dispatcher',
        ),
        'Symfony\\Component\\ErrorHandler\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/error-handler',
        ),
        'Symfony\\Component\\Dotenv\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/dotenv',
        ),
        'Symfony\\Component\\DependencyInjection\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/dependency-injection',
        ),
        'Symfony\\Component\\Console\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/console',
        ),
        'Symfony\\Component\\Config\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/config',
        ),
        'Symfony\\Component\\Clock\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/clock',
        ),
        'Symfony\\Component\\Cache\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/cache',
        ),
        'Symfony\\Bundle\\TwigBundle\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/twig-bundle',
        ),
        'Symfony\\Bundle\\SecurityBundle\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/security-bundle',
        ),
        'Symfony\\Bundle\\MonologBundle\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/monolog-bundle/src',
        ),
        'Symfony\\Bundle\\FrameworkBundle\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/framework-bundle',
        ),
        'Symfony\\Bridge\\Twig\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/twig-bridge',
        ),
        'Symfony\\Bridge\\Monolog\\' => 
        array (
            0 => __DIR__ . '/..' . '/symfony/monolog-bridge',
        ),
        'Soundasleep\\' => 
        array (
            0 => __DIR__ . '/..' . '/soundasleep/html2text/src',
        ),
        'Solarium\\' => 
        array (
            0 => __DIR__ . '/..' . '/solarium/solarium/src',
        ),
        'RRule\\' => 
        array (
            0 => __DIR__ . '/..' . '/rlanvin/php-rrule/src',
        ),
        'Psr\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/log/src',
        ),
        'Psr\\Http\\Message\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/http-factory/src',
            1 => __DIR__ . '/..' . '/psr/http-message/src',
        ),
        'Psr\\Http\\Client\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/http-client/src',
        ),
        'Psr\\EventDispatcher\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/event-dispatcher/src',
        ),
        'Psr\\Container\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/container/src',
        ),
        'Psr\\Clock\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/clock/src',
        ),
        'Psr\\Cache\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/cache/src',
        ),
        'Phpro\\ApiProblem\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpro/api-problem/src',
        ),
        'Phpro\\ApiProblemBundle\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpro/api-problem-bundle/src',
        ),
        'PHPStan\\PhpDocParser\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpstan/phpdoc-parser/src',
        ),
        'Overblog\\GraphQLBundle\\' => 
        array (
            0 => __DIR__ . '/..' . '/overblog/graphql-bundle/src',
        ),
        'Opis\\Uri\\' => 
        array (
            0 => __DIR__ . '/..' . '/opis/uri/src',
        ),
        'Opis\\String\\' => 
        array (
            0 => __DIR__ . '/..' . '/opis/string/src',
        ),
        'Opis\\JsonSchema\\' => 
        array (
            0 => __DIR__ . '/..' . '/opis/json-schema/src',
        ),
        'Murtukov\\PHPCodeGenerator\\' => 
        array (
            0 => __DIR__ . '/..' . '/murtukov/php-code-generator/src',
        ),
        'Monolog\\' => 
        array (
            0 => __DIR__ . '/..' . '/monolog/monolog/src/Monolog',
        ),
        'Lexik\\Bundle\\JWTAuthenticationBundle\\' => 
        array (
            0 => __DIR__ . '/..' . '/lexik/jwt-authentication-bundle',
        ),
        'League\\HTMLToMarkdown\\' => 
        array (
            0 => __DIR__ . '/..' . '/league/html-to-markdown/src',
        ),
        'League\\Csv\\' => 
        array (
            0 => __DIR__ . '/..' . '/league/csv/src',
        ),
        'Lcobucci\\JWT\\' => 
        array (
            0 => __DIR__ . '/..' . '/lcobucci/jwt/src',
        ),
        'JsonMachine\\' => 
        array (
            0 => __DIR__ . '/..' . '/halaxa/json-machine/src',
        ),
        'GraphQL\\' => 
        array (
            0 => __DIR__ . '/..' . '/webonyx/graphql-php/src',
        ),
        'Eluceo\\iCal\\' => 
        array (
            0 => __DIR__ . '/..' . '/eluceo/ical/src',
        ),
        'Egulias\\EmailValidator\\' => 
        array (
            0 => __DIR__ . '/..' . '/egulias/email-validator/src',
        ),
        'Doctrine\\Deprecations\\' => 
        array (
            0 => __DIR__ . '/..' . '/doctrine/deprecations/src',
        ),
        'Doctrine\\Common\\Lexer\\' => 
        array (
            0 => __DIR__ . '/..' . '/doctrine/lexer/src',
        ),
        'Cron\\' => 
        array (
            0 => __DIR__ . '/..' . '/dragonmantank/cron-expression/src/Cron',
        ),
        'Atoolo\\WebAccount\\' => 
        array (
            0 => __DIR__ . '/..' . '/atoolo/web-account-bundle/src',
        ),
        'Atoolo\\Seo\\' => 
        array (
            0 => __DIR__ . '/..' . '/atoolo/seo-bundle/src',
        ),
        'Atoolo\\Security\\' => 
        array (
            0 => __DIR__ . '/..' . '/atoolo/security-bundle/src',
        ),
        'Atoolo\\Search\\' => 
        array (
            0 => __DIR__ . '/..' . '/atoolo/search-bundle/src',
        ),
        'Atoolo\\Runtime\\Check\\' => 
        array (
            0 => __DIR__ . '/..' . '/atoolo/runtime-check-bundle/src',
        ),
        'Atoolo\\Runtime\\' => 
        array (
            0 => __DIR__ . '/..' . '/atoolo/runtime/src',
        ),
        'Atoolo\\Rewrite\\' => 
        array (
            0 => __DIR__ . '/..' . '/atoolo/rewrite-bundle/src',
        ),
        'Atoolo\\Resource\\' => 
        array (
            0 => __DIR__ . '/..' . '/atoolo/resource-bundle/src',
        ),
        'Atoolo\\Microsite\\' => 
        array (
            0 => __DIR__ . '/..' . '/atoolo/microsite-bundle/src',
        ),
        'Atoolo\\GraphQL\\Search\\' => 
        array (
            0 => __DIR__ . '/..' . '/atoolo/graphql-search-bundle/src',
        ),
        'Atoolo\\Form\\' => 
        array (
            0 => __DIR__ . '/..' . '/atoolo/form-bundle/src',
        ),
        'Atoolo\\EventsCalendar\\' => 
        array (
            0 => __DIR__ . '/..' . '/atoolo/events-calendar-bundle/src',
        ),
        'Atoolo\\Deployment\\' => 
        array (
            0 => __DIR__ . '/..' . '/atoolo/deployment-bundle/src',
        ),
        'Atoolo\\CityGov\\' => 
        array (
            0 => __DIR__ . '/..' . '/atoolo/citygov-bundle/src',
        ),
        'Atoolo\\CityCall\\' => 
        array (
            0 => __DIR__ . '/..' . '/atoolo/citycall-bundle/src',
        ),
        'App\\Tests\\' => 
        array (
            0 => __DIR__ . '/../..' . '/tests',
        ),
        'App\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'DateError' => __DIR__ . '/..' . '/symfony/polyfill-php83/Resources/stubs/DateError.php',
        'DateException' => __DIR__ . '/..' . '/symfony/polyfill-php83/Resources/stubs/DateException.php',
        'DateInvalidOperationException' => __DIR__ . '/..' . '/symfony/polyfill-php83/Resources/stubs/DateInvalidOperationException.php',
        'DateInvalidTimeZoneException' => __DIR__ . '/..' . '/symfony/polyfill-php83/Resources/stubs/DateInvalidTimeZoneException.php',
        'DateMalformedIntervalStringException' => __DIR__ . '/..' . '/symfony/polyfill-php83/Resources/stubs/DateMalformedIntervalStringException.php',
        'DateMalformedPeriodStringException' => __DIR__ . '/..' . '/symfony/polyfill-php83/Resources/stubs/DateMalformedPeriodStringException.php',
        'DateMalformedStringException' => __DIR__ . '/..' . '/symfony/polyfill-php83/Resources/stubs/DateMalformedStringException.php',
        'DateObjectError' => __DIR__ . '/..' . '/symfony/polyfill-php83/Resources/stubs/DateObjectError.php',
        'DateRangeError' => __DIR__ . '/..' . '/symfony/polyfill-php83/Resources/stubs/DateRangeError.php',
        'Deprecated' => __DIR__ . '/..' . '/symfony/polyfill-php84/Resources/stubs/Deprecated.php',
        'NoDiscard' => __DIR__ . '/..' . '/symfony/polyfill-php85/Resources/stubs/NoDiscard.php',
        'Normalizer' => __DIR__ . '/..' . '/symfony/polyfill-intl-normalizer/Resources/stubs/Normalizer.php',
        'Override' => __DIR__ . '/..' . '/symfony/polyfill-php83/Resources/stubs/Override.php',
        'ReflectionConstant' => __DIR__ . '/..' . '/symfony/polyfill-php84/Resources/stubs/ReflectionConstant.php',
        'SQLite3Exception' => __DIR__ . '/..' . '/symfony/polyfill-php83/Resources/stubs/SQLite3Exception.php',
        '©' => __DIR__ . '/..' . '/symfony/cache/Traits/ValueWrapper.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit75e7f8d848176580e9902a32f6f14640::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit75e7f8d848176580e9902a32f6f14640::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit75e7f8d848176580e9902a32f6f14640::$classMap;

        }, null, ClassLoader::class);
    }
}
