<?php

// platform_check.php @generated by Composer

$issues = array();

if (!(PHP_VERSION_ID >= 80300)) {
    $issues[] = 'Your Composer dependencies require a PHP version ">= 8.3.0". You are running ' . PHP_VERSION . '.';
}

$missingExtensions = array();
extension_loaded('ctype') || $missingExtensions[] = 'ctype';
extension_loaded('curl') || $missingExtensions[] = 'curl';
extension_loaded('date') || $missingExtensions[] = 'date';
extension_loaded('dom') || $missingExtensions[] = 'dom';
extension_loaded('fileinfo') || $missingExtensions[] = 'fileinfo';
extension_loaded('filter') || $missingExtensions[] = 'filter';
extension_loaded('iconv') || $missingExtensions[] = 'iconv';
extension_loaded('intl') || $missingExtensions[] = 'intl';
extension_loaded('json') || $missingExtensions[] = 'json';
extension_loaded('libxml') || $missingExtensions[] = 'libxml';
extension_loaded('openssl') || $missingExtensions[] = 'openssl';
extension_loaded('posix') || $missingExtensions[] = 'posix';
extension_loaded('simplexml') || $missingExtensions[] = 'simplexml';
extension_loaded('sodium') || $missingExtensions[] = 'sodium';
extension_loaded('sysvsem') || $missingExtensions[] = 'sysvsem';
extension_loaded('xml') || $missingExtensions[] = 'xml';
extension_loaded('xmlreader') || $missingExtensions[] = 'xmlreader';
extension_loaded('xmlwriter') || $missingExtensions[] = 'xmlwriter';
extension_loaded('zend opcache') || $missingExtensions[] = 'zend opcache';
extension_loaded('zip') || $missingExtensions[] = 'zip';

if ($missingExtensions) {
    $issues[] = 'Your Composer dependencies require the following PHP extensions to be installed: ' . implode(', ', $missingExtensions) . '.';
}

if ($issues) {
    if (!headers_sent()) {
        header('HTTP/1.1 500 Internal Server Error');
    }
    if (!ini_get('display_errors')) {
        if (PHP_SAPI === 'cli' || PHP_SAPI === 'phpdbg') {
            fwrite(STDERR, 'Composer detected issues in your platform:' . PHP_EOL.PHP_EOL . implode(PHP_EOL, $issues) . PHP_EOL.PHP_EOL);
        } elseif (!headers_sent()) {
            echo 'Composer detected issues in your platform:' . PHP_EOL.PHP_EOL . str_replace('You are running '.PHP_VERSION.'.', '', implode(PHP_EOL, $issues)) . PHP_EOL.PHP_EOL;
        }
    }
    trigger_error(
        'Composer detected issues in your platform: ' . implode(' ', $issues),
        E_USER_ERROR
    );
}
