<?php

// atoolo_runtime.php @generated by Atoolo Runtime

$runtime = $_SERVER['ATOOLO_RUNTIME'] ?? $_ENV['ATOOLO_RUNTIME'] ?? 'Atoolo\\Runtime\\AtooloRuntime';
$runtime = new $runtime(
  dirname(__DIR__, 1),
  ($_SERVER['ATOOLO_RUNTIME_OPTIONS'] ?? $_ENV['ATOOLO_RUNTIME_OPTIONS'] ?? []) + array (
  'atoolo/runtime' => 
  array (
    'executor' => 
    array (
      0 => 'Atoolo\\Runtime\\Executor\\EnvSetter',
      1 => 'Atoolo\\Runtime\\Executor\\IniSetter',
      2 => 'Atoolo\\Runtime\\Executor\\UmaskSetter',
      3 => 'Atoolo\\Runtime\\Executor\\UserValidator',
    ),
  ),
  '__root__' => 
  array (
    'ini' => 
    array (
      'set' => 
      array (
        'date.timezone' => 'Europe/Berlin',
      ),
    ),
    'umask' => '0002',
    'users' => 
    array (
      0 => 'www-data',
      1 => '{SCRIPT_OWNER}',
    ),
  ),
)
);
$runtime->run();
