name: E2E Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          tools: composer, phive
      - name: Add hosts to /etc/hosts
        run: |
          sudo echo "127.0.0.1 atoolo-e2e-test" | sudo tee -a /etc/hosts
      - name: Test
        run: bin/run.sh
