name: Run E2E Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install PHP 8.3
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
      - name: Test
        run: bin/run.sh
